services:
  - type: web
    name: songhub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    disk:
      name: songhub-data
      mountPath: /opt/render/project/src
      sizeGB: 1